# src/odoo_doctor/core/scaffold.py
"""Starter project for a third-party rule pack (`odoo-doctor rules new`).

Pure text generation plus one writer. The generated rule imports only from
``odoo_doctor.plugin_api``, the stable surface (docs/custom-rules.md), and ships with
tests that run without installing the package.
"""

from __future__ import annotations

import re
from pathlib import Path

from odoo_doctor import __version__

_RULE_NAME = re.compile(r"^[a-z][a-z0-9]*(-[a-z0-9]+)*$")


def validate_rule_name(name: str) -> None:
    """Raise ValueError unless *name* is a free kebab-case rule name."""
    if not _RULE_NAME.match(name):
        raise ValueError(
            f"'{name}' is not a valid rule name: use lowercase letters, digits and "
            "single hyphens, starting with a letter (e.g. no-print-statements)"
        )
    import odoo_doctor.cli.app  # noqa: F401  (registers every built-in rule)
    from odoo_doctor.rules.registry import default_registry

    if name in default_registry:
        raise ValueError(
            f"'{name}' already exists as a built-in rule; a plugin cannot replace it"
        )


def module_name(rule_name: str) -> str:
    """`no-print-statements` -> `no_print_statements`."""
    return rule_name.replace("-", "_")


_PYPROJECT = """\
[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "odoo-doctor-rules-@@RULE@@"
version = "0.1.0"
description = "Odoo Doctor rule: @@RULE@@"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["odoo-doctor>=@@VERSION@@"]

[project.optional-dependencies]
dev = ["pytest"]

[project.entry-points."odoo_doctor.rules"]
@@MOD@@ = "odoo_doctor_rules_@@MOD@@.rules"

[tool.setuptools.packages.find]
where = ["src"]
"""

_RULES = '''\
"""Rule `@@RULE@@`. Replace the starter check below with your own."""

from __future__ import annotations

import ast
from pathlib import Path

from odoo_doctor.plugin_api import Diagnostic, read_source, rule

ODOO_DOCTOR_PLUGIN_API = 1  # the plugin API version this module targets


@rule(
    name="@@RULE@@",
    category="Maintainability",
    tier="P3",
    severity="info",
    default_confidence="high",  # only high-confidence findings change the score
    needs_context=False,  # a file rule: called once per .py file of each addon
    min_version="14.0",
)
def check_@@MOD@@(
    file_path: Path, module_name: str, odoo_version: str
) -> list[Diagnostic]:
    """Starter check: flag `print()` calls."""
    source = read_source(file_path)
    if source is None:
        return []
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    diagnostics = []
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id == "print"
        ):
            diagnostics.append(
                Diagnostic(
                    module=module_name,
                    file_path=str(file_path),
                    line=node.lineno,
                    column=node.col_offset,
                    rule="@@RULE@@",
                    category="Maintainability",
                    severity="info",
                    tier="P3",
                    source="native",
                    confidence="high",
                    title="print() left in code",
                    message="A print() call writes to stdout instead of the log.",
                    help="Use the logging module (`_logger.info(...)`).",
                    odoo_version=odoo_version,
                )
            )
    return diagnostics
'''

_TEST = '''\
"""Tests for `@@RULE@@`: build a small source file, run the rule, assert the findings."""

from __future__ import annotations

from pathlib import Path

from odoo_doctor_rules_@@MOD@@.rules import check_@@MOD@@


def _run(tmp_path: Path, source: str):
    path = tmp_path / "models.py"
    path.write_text(source)
    return check_@@MOD@@(path, "demo", "17.0")


def test_flags_the_bad_pattern(tmp_path: Path):
    diagnostics = _run(tmp_path, "def run():\\n    print('debug')\\n")
    assert [d.rule for d in diagnostics] == ["@@RULE@@"]
    assert diagnostics[0].line == 2


def test_clean_code_has_no_findings(tmp_path: Path):
    assert _run(tmp_path, "def run():\\n    return 1\\n") == []


def test_a_file_that_does_not_parse_is_skipped(tmp_path: Path):
    assert _run(tmp_path, "def broken(:\\n") == []
'''

_README = """\
# odoo-doctor-rules-@@RULE@@

An [Odoo Doctor](https://github.com/minhhq-a1/odoo-doctor) rule pack. It was generated by
`odoo-doctor rules new @@RULE@@` and holds one starter rule that flags `print()` calls.

## Develop

```bash
pip install -e ".[dev]"
pytest
```

Edit `src/odoo_doctor_rules_@@MOD@@/rules.py` and `tests/test_@@MOD@@.py`. Import only from
`odoo_doctor.plugin_api`: it is the stable surface (see the
[custom rules guide](https://github.com/minhhq-a1/odoo-doctor/blob/main/docs/custom-rules.md)).
Add more rules in the same module (or more modules, each listed under
`[project.entry-points."odoo_doctor.rules"]`).

## Use it

Plugins are off by default because they run code. In the `odoo-doctor.toml` of the project
you scan:

```toml
[plugins]
enabled = true
allow = ["@@MOD@@"]
```

then `odoo-doctor scan .`. Findings go through the normal pipeline, so `[severity]`,
`[ignore]` and `# odoo-doctor: disable=@@RULE@@` work as for built-in rules.

## Publish

Name the package `odoo-doctor-rules-<topic>` (already the case here) so it is easy to find on
PyPI, and build it with `python -m build`.
"""

_GITIGNORE = "__pycache__/\n*.egg-info/\nbuild/\ndist/\n.pytest_cache/\n"


def render_plugin_scaffold(rule_name: str) -> dict[str, str]:
    """Relative path -> file content of a starter rule pack for *rule_name*."""
    mod = module_name(rule_name)
    root = f"odoo-doctor-rules-{rule_name}"
    pkg = f"{root}/src/odoo_doctor_rules_{mod}"

    def fill(template: str) -> str:
        return (
            template.replace("@@RULE@@", rule_name)
            .replace("@@MOD@@", mod)
            .replace("@@VERSION@@", __version__)
        )

    return {
        f"{root}/pyproject.toml": fill(_PYPROJECT),
        f"{root}/README.md": fill(_README),
        f"{root}/.gitignore": _GITIGNORE,
        f"{pkg}/__init__.py": "",
        f"{pkg}/rules.py": fill(_RULES),
        f"{root}/tests/test_{mod}.py": fill(_TEST),
    }


def write_scaffold(rule_name: str, out_dir: Path) -> Path:
    """Write the starter project under *out_dir*; return its directory.

    Raises ValueError for a bad or taken rule name, FileExistsError if the project
    directory already exists (nothing is written then).
    """
    validate_rule_name(rule_name)
    project = Path(out_dir) / f"odoo-doctor-rules-{rule_name}"
    if project.exists():
        raise FileExistsError(str(project))
    for relative, content in render_plugin_scaffold(rule_name).items():
        target = Path(out_dir) / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    return project
